package ru.itis.tests;// Generated by Selenium IDE

import io.qameta.allure.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.testng.Assert;
import org.testng.annotations.Test;
import ru.itis.data.User;

public class AuthorizationTest extends TestBase {

    @Epic("TESTING FOR Motivator App ")
    @Feature(value = "Authorization")
    @Severity(SeverityLevel.BLOCKER)
    @Description("In this test we will login as user")
    @Story(value = "Test for login with correct credentials")
    @Test
    public void authorization() {
        User user = User.builder()
                .login("test")
                .password("testpass")
                .build();
        main.goTo().signInButtonClick();
        String expectedLogin = signIn
                                .signIn(user)
                                .authorizedLogin();

        Assert.assertEquals(expectedLogin, "test");
    }

}
