package ru.itis.Tests;// Generated by Selenium IDE

import io.qameta.allure.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.testng.annotations.Test;
import ru.itis.Data.User;

public class AuthorizationTest extends TestBase {

  @Epic("TESTING FOR https://thenewschool.dev/ ")
  @Feature(value = "Authorization")
  @Severity(SeverityLevel.BLOCKER)
  @Description("In this test we will login with coach user")
  @Story(value = "Test for login with correct credentials")
  @Test
  public void authorization() {
    signIn.goTo()
            .signIn(User.builder().
                    login("login").
                    password("Password").
                    build());
  }

  @Epic("TESTING FOR https://thenewschool.dev/ ")
  @Feature(value = "Authorization")
  @Severity(SeverityLevel.BLOCKER)
  @Description("In this test we will login withstudent user")
  @Story(value = "Test for login with correct credentials")
  @Test
  public void authorizationStudent() {
    driver.get("https://thenewschool.dev/login");
    driver.manage().window().setSize(new Dimension(1058, 780));
    driver.findElement(By.cssSelector("button")).click();
  }
}
