package ru.itis.tests;// Generated by Selenium IDE

import io.qameta.allure.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.testng.annotations.Test;
import ru.itis.data.User;

public class AuthorizationTest extends TestBase {

    @Epic("TESTING FOR https://thenewschool.dev/ ")
    @Feature(value = "Authorization")
    @Severity(SeverityLevel.BLOCKER)
    @Description("In this test we will login with coach user")
    @Story(value = "Test for login with correct credentials")
    @Test
    public void authorization() {

        signIn.goTo()
                .signIn(User.builder().
                        login("login").
                        password("password").
                        build());

    }
}
